name: Dynamic Matrix Build and Push with Derived Paths

on:
  workflow_dispatch:
    inputs:
      services:
        description: "Comma-separated list of services to build (no spaces)"
        required: true
        default: '["sui-gas-pool"]'
      version:
        description: "Version number for the services (eg - v1/v2)"
        required: true
        default: "v1"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ${{ fromJSON(inputs.services) }}

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Update submodules
        run: |
          git submodule sync
          git submodule update --init --recursive

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Build and Push Docker Images
      - name: Build and Push ${{ matrix.service }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          SERVICE_NAME="${{ matrix.service }}"
          echo "Building and pushing $SERVICE_NAME with version ${{ inputs.version }}"
          DOCKER_BUILDKIT=1 docker build --secret id=sentry_token,env=SENTRY_AUTH_TOKEN -t aeon/$SERVICE_NAME:${{ inputs.version }} -f docker/Dockerfile .
          docker tag aeon/$SERVICE_NAME:${{ inputs.version }} 533267399827.dkr.ecr.eu-west-1.amazonaws.com/$SERVICE_NAME:${{ inputs.version }}
          docker push 533267399827.dkr.ecr.eu-west-1.amazonaws.com/$SERVICE_NAME:${{ inputs.version }}
